### ISSUE TITLE
Make a first inventory of pipelines we care about

### ISSUE THREAD

**Issue by surchs** [nipoppy/pipeline-catalog#2]
The world is big, but time is short. So I'd say we add pipelines as we come across them. We already have some listed here: https://github.com/nipoppy/nipoppy/tree/756fb3532cc201986300ae2b0095429e179e5a9a/nipoppy/data/descriptors that we can start with. These are (with their versions):

- bidscoiner
  - 4.3.2
- bidseditor (is this a separate thing?)
  - 4.3.2
- bidsmapper (is this a separate thing?)
  - 4.3.2
- dcm2bids
  - 3.1.0
- dcm2bids_helper (do we really want to represent this separately as a pipeline?)
  - 3.1.0
- fmriprep
  - 20.2.7
  - 23.1.3
- heudiconv
  - 0.12.2
- mriqc
  - 23.1.0

**Comment by michellewang** [comment]
- `bidscoiner`, `bidseditor` and `bidsmapper` are all part of BIDScoin
- BIDScoin, `dcm2bids` and `heudiconv` are all BIDS converters ("BIDS pipelines" in Nipoppy terminology) so not very relevant for Neurobagel. I think in the pipeline catalog we will have to make this differentiation (BIDS pipeline vs processing pipeline vs eventually extraction pipeline)
